FROM golang:alpine AS builder
# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache git
WORKDIR /app
COPY . .
# Fetch dependencies.
# Using go get.
# RUN go get -d github.com/go-sql-driver/mysql
# RUN go get -d -v
# Build the binary.
# RUN go mod init main
RUN go build -o main
# ############################
# # STEP 2 build a small image
# ############################
# FROM scratch
# # Copy our static executable.
# COPY --from=builder /go/bin/hello /go/bin/hello
# Run the hello binary.
ENTRYPOINT ["/app/main"]
EXPOSE 8088